language: cpp

os: linux
dist: xenial
sudo: required

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-6
            - gcc-6
            - libeigen3-dev
            - libpng-dev
            - libtiff-dev
            - libopenexr-dev
            - libqt5*
            - qt5-default
            - libboost-all-dev
            - libxerces-c-dev
            - libglewmx-dev
            - libfftw3-dev

script:
   - scons --cfg=./build/config-travis.py

after_failure:
   - cat config.log;

