Import('env', 'plugins')

plugins += env.SharedLibrary('addimages', ['addimages.cpp'])
plugins += env.SharedLibrary('joinrgb', ['joinrgb.cpp'])
plugins += env.SharedLibrary('cylclip', ['cylclip.cpp'])
plugins += env.SharedLibrary('kdbench', ['kdbench.cpp'])
plugins += env.SharedLibrary('tonemap', ['tonemap.cpp'])
#plugins += env.SharedLibrary('rdielprec', ['rdielprec.cpp'])

conf = Configure(env)
buildOpenImageDenoise = conf.CheckCXXHeader('OpenImageDenoise/oidn.hpp')
env = conf.Finish()

if buildOpenImageDenoise:
   plugins += env.SharedLibrary('denoise', ['denoise.cpp'], LIBS = ['OpenImageDenoise'])

Export('plugins')
